### ISSUE TITLE
Download link not working

### ISSUE THREAD

**Issue by le-ro-la** [Subtivals/subtivals#326]
Hi.
We purchased the app from the site subtivals.org (139 EU)
We received a link from payhip
But when we try to download a message appears that is not possible.
So we wrote to payhip and they return us that they can't put an exe for download, for security.
Then they tell us to be in contact with Subtivals team. We did it but not answers yet.
Please, help us ... we're ina a middle of a Movie Festival and need to use the app.
Thanks a lot.

Leonardo from Iguale. (iguale.com.br)

**Comment by leplatrem** [comment]
Weird. Never had such issues with Payhip.
I sent you an email mauricio@..

**Comment by le-ro-la** [comment]
Hi.
Please copy ***@***.*** and ***@***.***

Could you send a link for us?

Thanks

Em sáb., 20 de jan. de 2024 16:00, Mathieu Leplatre <
***@***.***> escreveu:

**Comment by CarlosSubbabel** [comment]
Hi, I'm having the same issue. Screenshots attached. It's urgent.
![Captura de pantalla 2024-02-08 a las 16 21 42](https://github.com/Subtivals/subtivals/assets/159301649/90d94e6f-1401-471b-9d2f-33c18f417ac5)
![Captura de pantalla 2024-02-08 a las 16 21 54](https://github.com/Subtivals/subtivals/assets/159301649/eab285ca-af3c-407a-a28b-20dae331384a)

**Comment by leplatrem** [comment]
Payhip now rejects `.dmg` and `.exe` files. 
This should be fixed now, I updated the store with `.zip` file.

I'm really sorry for the inconvenience encountered.
